# Dependencies
markdown:	kramdown
highlighter:    pygments
# Permalinks
permalink:	/project/:title

# Setup
title:            NSchrading
tagline:          "Nic Schrading's personal website."
description:      'A place to get information on all things Nic Schrading.'
url:              https://nschrading.github.io/
baseurl:          
commentsystem:    google
disqus:           example

author:
  name:           J Nicolas Schrading
  url:            https://nschrading.github.io/

paginate:         5

# Custom vars
cover:            /assets/images/earthrise.png

social:
  - icon:         twitter
    url:          https://twitter.com/nschrading
    desc:         Follow me on Twitter

  - icon:         github
    url:          https://github.com/nschrading
    desc:         Fork me on GitHub

  - icon:         linkedin
    url:          https://www.linkedin.com/pub/j-nicolas-schrading/65/56b/b19
    desc:         Connect with me on LinkedIn

menu:
  - title:        Home
    url:          /

  - title:        About
    url:          /about

  - title:        Data
    url:          /data

copyright:
  author:         J Nicolas Schrading
  url:            https://nschrading.github.io/
  type_title:     Some rights reserved
  type_url:       http://creativecommons.org/licenses/by-nc/2.5

parallax:         false

# Google Analytics (add the UA Code, e.g.: UA-xxxxxxxx-1)
google_analytics:  UA-65114006-1

# Default Theme Color for Chrome on Android Lollipop (Use RGB ColorCode without `#`, e.g.: `db5945`)
theme_color:       7E9576
